apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v7eo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v7eo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v7eo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v7eo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v7eo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zibl-tenant/rhtap-demo-app/hacbs-test-project-v7eo@sha256:cf4098ceec958da46078aaad4c47de8a9134f473dccfa587b6ef9ee88f2f6f90
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
